core.entity_form_display.group.course_advanced.default:
  expected_config: {}
  update_actions:
    delete: {}
    add:
      third_party_settings:
        field_group:
          group_additional_details:
            children:
              - group_related_courses
            format_settings:
              classes: social-collapsible-fieldset
              description: ''
              id: ''
              open: false
              required_fields: true
            format_type: details
            label: 'Additional information'
            parent_name: ''
            region: content
            weight: 2
          group_settings:
            children:
              - group_date_and_time
            format_settings:
              open: false
    change:
      content:
        field_course_order:
          weight: 3
        field_course_redirect_url:
          weight: 4
        field_course_type:
          type: options_buttons
        field_group_description:
          weight: 7
        field_group_image:
          weight: 6
      third_party_settings:
        field_group:
          group_date_and_time:
            parent_name: group_settings
            weight: 2
          group_related_courses:
            parent_name: group_additional_details
          group_settings:
            format_settings:
              classes: social-collapsible-fieldset
            format_type: details
          group_information:
            label: 'Basic information'
