core.entity_form_display.node.course_section.default:
  expected_config: { }
  update_actions:
    delete:
      hidden:
        uid: true
    add:
      third_party_settings:
        field_group:
          group_settings:
            children:
              - field_course_section_redirect
              - status
            format_settings:
              classes: social-collapsible-fieldset
              description: ''
              id: ''
              open: false
              required_fields: true
            format_type: details
            label: Settings
            parent_name: ''
            region: hidden
            weight: 20
          group_access_permissions:
            children:
              - groups
            format_settings:
              classes: ''
              description: ''
              id: ''
              required_fields: true
            format_type: fieldset
            label: 'Access permissions'
            parent_name: ''
            region: content
            weight: 0
    change:
      third_party_settings:
        field_group:
          group_section_content:
            label: 'Basic information'
